### ISSUE TITLE
Ubuntu -16.04  minimal - Installation error

### ISSUE THREAD

**Issue by ghost** [bablokb/jasper#4]
Hello, 

i m using ubuntu 16.040 minimal found here --> https://help.ubuntu.com/community/Installation/MinimalCD

i m trying to make jasper works :
with u script i have this error 
```

`stagiaire@Jasper:~$ sudo jasper --debug
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/stagiaire/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python package 'pocketsphinx' found: '/usr/lib/python2.7/dist-packages/pocketsphinx/__init__.py'
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'espeak'...
DEBUG:client.diagnose:Executable 'espeak' found: '/usr/bin/espeak'
DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
ERROR:client.stt:hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/usr/local/lib/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/usr/local/lib/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/usr/local/lib/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/usr/local/lib/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/usr/local/lib/jasper/client/stt.py", line 105, in __init__
    raise RuntimeError(msg)
RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.
`
```

do u have a solution for that please ?

**Comment by tirdtoon** [comment]
try this ->
wget http://downloads.sourceforge.net/project/cmusphinx/sphinxbase/0.8/sphinxbase-0.8.tar.gz
tar -zxvf sphinxbase-0.8.tar.gz
cd ~/sphinxbase-0.8/
mv config.guess config.guess.old
./autogen.sh
make
sudo make install
wget http://downloads.sourceforge.net/project/cmusphinx/pocketsphinx/0.8/pocketsphinx-0.8.tar.gz
tar -zxvf pocketsphinx-0.8.tar.gz
cd ~/pocketsphinx-0.8/
mv config.guess config.guess.old
./autogen.sh
make
sudo make install
cd ..
sudo easy_install pocketsphinx
